<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<SpaRoot>..\adventureworks.client</SpaRoot>
		<SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
		<SpaProxyServerUrl>https://localhost:51037</SpaProxyServerUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.21.0" />
		<PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="8.5.0" />

		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.14" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.14" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.14">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\adventureworks.client\adventureworks.client.esproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>

</Project>